title: AUAAS
description: Official website of the AUAAS Student Club.
baseurl: "/" # Leave empty for root
url: "https://auaas.github.io"

theme: null # No default theme
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
